# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""
ExecutionRegistry — single-process in-memory idempotency store.

Phase 10E Batch 1 — Idempotency Contract
Phase 10E Batch 3 — Reconciliation support (intent snapshot, ReconciliationRecord)

SINGLE-PROCESS SAFETY
---------------------
Idempotency guarantees provided by this registry are valid only within one
process instance. Distributed / multi-replica idempotency requires a shared
external store and is out of scope for Batch 1.

Identity relationships
----------------------
execution_id    : One logical execution attempt. Generated by BaseActionExecutor
                  before the write. Stable across guard checks and the write call.
idempotency_key : Identity of the intended logical mutation. Caller-supplied via
                  ActionProposal.idempotency_key. Same key + same capability =
                  same logical operation; re-submission does not produce a second
                  physical mutation.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any

from .outcome import ExecutionOutcome
from .reconciliation import ExecutionIntent, ReconciliationRecord, ReconciliationOutcome

if TYPE_CHECKING:
    pass

logger = logging.getLogger(__name__)


@dataclass
class ExecutionRecord:
    """A single recorded execution attempt."""

    execution_id: str
    idempotency_key: str | None
    capability: str
    proposal_id: str
    started_at: datetime
    outcome: ExecutionOutcome | None = None  # None = in-progress
    completed_at: datetime | None = None
    result: Any = None  # ActionExecutionResult once complete
    intent: ExecutionIntent | None = None  # Immutable snapshot captured at begin() time
    reconciliation: ReconciliationRecord | None = None  # Set by set_reconciliation()

    @property
    def effective_status(self) -> str:
        """
        Derived operational view of this execution record.

        Returns
        -------
        "in_progress"           — outcome is None (write not yet complete)
        "effectively_executed"  — UNKNOWN + reconciliation CONFIRMED_EXECUTED
        "effectively_not_executed" — UNKNOWN + reconciliation CONFIRMED_NOT_EXECUTED
        "unknown"               — UNKNOWN + no reconciliation or INDETERMINATE
        "{outcome.value}"       — any other completed outcome
        """
        if self.outcome is None:
            return "in_progress"
        if self.outcome == ExecutionOutcome.UNKNOWN:
            if self.reconciliation is None:
                return "unknown"
            if self.reconciliation.outcome == ReconciliationOutcome.CONFIRMED_EXECUTED:
                return "effectively_executed"
            if (
                self.reconciliation.outcome
                == ReconciliationOutcome.CONFIRMED_NOT_EXECUTED
            ):
                return "effectively_not_executed"
            return "unknown"  # INDETERMINATE
        return self.outcome.value


class ExecutionRegistry:
    """
    Single-process in-memory idempotency store for warehouse write executions.

    Usage
    -----
    At executor startup:
        registry = ExecutionRegistry()

    In BaseActionExecutor.execute():
        existing = registry.begin(execution_id, idempotency_key, capability, proposal_id)
        if existing is not None:
            return _idempotent_result(existing)
        # ... perform write ...
        registry.complete(execution_id, outcome, result)
        # OR on ambiguous write:
        registry.mark_unknown(execution_id)
    """

    def __init__(self) -> None:
        self._by_execution_id: dict[str, ExecutionRecord] = {}
        self._by_idempotency_key: dict[str, ExecutionRecord] = {}

    def begin(
        self,
        execution_id: str,
        idempotency_key: str | None,
        capability: str,
        proposal_id: str,
        intent: ExecutionIntent | None = None,
    ) -> ExecutionRecord | None:
        """
        Register the start of a new execution attempt.

        Parameters
        ----------
        intent : ExecutionIntent | None
            Compact immutable snapshot of write intent. Stored in the
            ExecutionRecord so reconciliation has everything it needs without
            a reference back to the original ActionProposal.

        Returns
        -------
        None
            This is a fresh execution — proceed with the write.
        ExecutionRecord
            A prior execution with the same execution_id or idempotency_key
            was found. The caller should return an idempotent result rather
            than executing again.
        """
        # Check for duplicate execution_id (idempotent retry of the same attempt)
        if execution_id in self._by_execution_id:
            existing = self._by_execution_id[execution_id]
            logger.debug(
                "ExecutionRegistry: duplicate execution_id=%s found (outcome=%s)",
                execution_id,
                existing.outcome,
            )
            return existing

        # Check for same logical operation (same idempotency_key + same capability)
        if idempotency_key is not None:
            idem_key = f"{capability}:{idempotency_key}"
            if idem_key in self._by_idempotency_key:
                existing = self._by_idempotency_key[idem_key]
                logger.debug(
                    "ExecutionRegistry: duplicate idempotency_key=%r capability=%s found "
                    "(prior execution_id=%s outcome=%s)",
                    idempotency_key,
                    capability,
                    existing.execution_id,
                    existing.outcome,
                )
                return existing

        # Fresh start — register the record
        record = ExecutionRecord(
            execution_id=execution_id,
            idempotency_key=idempotency_key,
            capability=capability,
            proposal_id=proposal_id,
            started_at=datetime.now(timezone.utc),
            intent=intent,
        )
        self._by_execution_id[execution_id] = record
        if idempotency_key is not None:
            idem_key = f"{capability}:{idempotency_key}"
            self._by_idempotency_key[idem_key] = record

        return None

    def complete(
        self,
        execution_id: str,
        outcome: ExecutionOutcome,
        result: Any,
    ) -> None:
        """Mark an execution as complete with its final outcome and result."""
        record = self._by_execution_id.get(execution_id)
        if record is None:
            logger.warning(
                "ExecutionRegistry.complete: unknown execution_id=%s", execution_id
            )
            return
        record.outcome = outcome
        record.completed_at = datetime.now(timezone.utc)
        record.result = result

    def mark_unknown(self, execution_id: str) -> None:
        """
        Mark an execution as UNKNOWN (ambiguous write — mutation may have occurred,
        response was lost). Prevents any automatic retry.
        """
        record = self._by_execution_id.get(execution_id)
        if record is None:
            logger.warning(
                "ExecutionRegistry.mark_unknown: unknown execution_id=%s", execution_id
            )
            return
        record.outcome = ExecutionOutcome.UNKNOWN
        record.completed_at = datetime.now(timezone.utc)
        logger.warning(
            "ExecutionRegistry: execution_id=%s marked UNKNOWN — "
            "reconciliation required before re-execution",
            execution_id,
        )

    def set_reconciliation(
        self, execution_id: str, record: ReconciliationRecord
    ) -> None:
        """
        Attach a ReconciliationRecord to an UNKNOWN execution.

        The original ExecutionOutcome.UNKNOWN is NOT rewritten — this is by
        design. Use ExecutionRecord.effective_status for the derived
        operational view after reconciliation.
        """
        existing = self._by_execution_id.get(execution_id)
        if existing is None:
            logger.warning(
                "ExecutionRegistry.set_reconciliation: unknown execution_id=%s",
                execution_id,
            )
            return
        if existing.outcome != ExecutionOutcome.UNKNOWN:
            logger.warning(
                "ExecutionRegistry.set_reconciliation: execution_id=%s outcome is %s, "
                "not UNKNOWN — reconciliation record stored but outcome is unchanged",
                execution_id,
                existing.outcome,
            )
        existing.reconciliation = record
        logger.info(
            "ExecutionRegistry: reconciliation stored execution_id=%s outcome=%s",
            execution_id,
            record.outcome.value,
        )

    def get_by_execution_id(self, execution_id: str) -> ExecutionRecord | None:
        return self._by_execution_id.get(execution_id)

    def get_by_idempotency_key(
        self, idempotency_key: str, capability: str
    ) -> ExecutionRecord | None:
        idem_key = f"{capability}:{idempotency_key}"
        return self._by_idempotency_key.get(idem_key)

    def __len__(self) -> int:
        return len(self._by_execution_id)

    def reset(self) -> None:
        """Clear all records. For test use only."""
        self._by_execution_id.clear()
        self._by_idempotency_key.clear()
